Update patch set 2
Patch Set 2:

I have tried on controller. I have not enabled congress in deployment time, but it seems to be there while not running. Just maybe because of this, I do not have everything in .conf file and fails:
  File "set_congress.py", line 39, in <module>
    set_drivers_config()
  File "set_congress.py", line 25, in set_drivers_config
    drivers = config.get('DEFAULT', 'drivers')
  File "/usr/lib64/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'drivers' in section: 'DEFAULT'
 
I wonder if our aodh problem was similar. I mean should the deployment enable it with some flag, so there would be some configuration already made (event_definitions.yaml)

Patch-set: 2