Update patch set 5
Patch Set 5:

Found syntax error and/or coding style violation(s) in the files modified by your patchset.

Python violation(s)
---
 doctor_tests/installer/apex.py:117:1: W293 blank line contains whitespace
 
 ^
 doctor_tests/installer/common/set_config.py:12:1: F401 'ConfigParser' imported but unused
 import ConfigParser
 ^
 doctor_tests/installer/common/set_config.py:50:5: F841 local variable 'config_modified' is assigned to but never used
     config_modified = False
     ^
 doctor_tests/installer/common/set_config.py:108:5: F841 local variable 'config_modified' is assigned to but never used
     config_modified = False
     ^
 doctor_tests/main.py:18:1: F401 'doctor_tests.common.utils.get_doctor_test_root_dir' imported but unused
 from doctor_tests.common.utils import get_doctor_test_root_dir
 ^
 doctor_tests/scenario/maintenance.py:67:33: E226 missing whitespace around arithmetic operator
         flavor_vcpus = int(vcpus/2)
                                 ^
 doctor_tests/user.py:17:1: F811 redefinition of unused 'ks_exceptions' from line 11
 from keystoneclient import exceptions as ks_exceptions
 ^
YAML violation(s)
---
 doctor_tests/maintenance_hot_tpl.yaml
   1:1       warning  missing document start ---  (document-start)
   35:20     error    too many spaces inside braces  (braces)
   35:42     error    too many spaces inside braces  (braces)
   37:25     error    too many spaces inside brackets  (brackets)
   37:35     error    too many spaces inside brackets  (brackets)
   43:31     error    too many spaces inside braces  (braces)
   43:42     error    too many spaces inside braces  (braces)
   43:61     error    too many spaces inside braces  (braces)
   43:63     error    too many spaces inside braces  (braces)
   48:19     error    too many spaces inside braces  (braces)
   48:44     error    too many spaces inside braces  (braces)
   49:16     error    too many spaces inside braces  (braces)
   49:41     error    too many spaces inside braces  (braces)
   52:4      error    wrong indentation: expected 4 but found 3  (indentation)
   56:14     error    too many spaces inside braces  (braces)
   56:38     error    too many spaces inside braces  (braces)
   63:18     error    too many spaces inside brackets  (brackets)
   63:34     error    too many spaces inside brackets  (brackets)
   68:14     error    too many spaces inside braces  (braces)
   68:33     error    too many spaces inside braces  (braces)
   73:15     error    too many spaces inside braces  (braces)
   73:38     error    too many spaces inside braces  (braces)
   78:20     error    too many spaces inside braces  (braces)
   78:56     error    too many spaces inside braces  (braces)
   79:19     error    too many spaces inside braces  (braces)
   79:42     error    too many spaces inside braces  (braces)
   81:25     error    too many spaces inside braces  (braces)
   81:47     error    too many spaces inside braces  (braces)
   83:21     error    too many spaces inside braces  (braces)
   83:49     error    too many spaces inside braces  (braces)
   88:15     error    too many spaces inside braces  (braces)
   88:41     error    too many spaces inside braces  (braces)
   93:20     error    too many spaces inside braces  (braces)
   93:56     error    too many spaces inside braces  (braces)
   94:19     error    too many spaces inside braces  (braces)
   94:42     error    too many spaces inside braces  (braces)
   96:25     error    too many spaces inside braces  (braces)
   96:47     error    too many spaces inside braces  (braces)
   101:21    error    too many spaces inside braces  (braces)
   101:47    error    too many spaces inside braces  (braces)
   102:19    error    too many spaces inside braces  (braces)
   102:31    error    too many spaces inside brackets  (brackets)
   102:62    error    too many spaces inside brackets  (brackets)
   102:64    error    too many spaces inside braces  (braces)
   108:12    error    too many spaces inside braces  (braces)
   108:45    error    too many spaces inside braces  (braces)
   116:12    error    too many spaces inside braces  (braces)
   116:42    error    too many spaces inside braces  (braces)

Patch-set: 5